"""Generate the approved independent-client table without retraining models."""
import argparse
from collections import defaultdict
import csv
import hashlib
import io
import itertools
import json
import math
from pathlib import Path
import statistics

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'results/reviewer_revision_20260831'
SOURCE = BASE / 'deadline_queue_20260920/traditional_reuse_matrix.csv'
COVERAGE = BASE / 'audit_20260910/traditional/traditional_full_coverage_runs.csv'
MAIN = BASE / 'revision_approved_20260920/main_classification_summary.csv'
OUT = BASE / 'revision_approval_20260924/traditional'
TEX = ROOT / 'paper_acs_latex/traditional_local_table_generated.tex'
DATASETS = ('BBBP', 'SIDER', 'Tox21', 'HIV', 'ToxCast')
ALPHAS = (.1, .5, 1.)
METHODS = ('LOCAL-ECFP-LOGREG', 'LOCAL-ECFP-NB', 'LOCAL-ECFP-RF')


def rows(path):
    with path.open(newline='') as stream:
        return list(csv.DictReader(stream))


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def key(row):
    return row['dataset'], float(row['alpha']), row['method'], int(row['seed'])


def summarize(records):
    expected = set(itertools.product(DATASETS, ALPHAS, METHODS, (0, 1, 2)))
    if len(records) != 135 or {key(r) for r in records} != expected:
        raise ValueError('Require all 135 unique independent-client conditions')
    groups = defaultdict(list)
    for record in records:
        value = float(record['primary_test_auc'])
        if not math.isfinite(value) or not 0 <= value <= 1:
            raise ValueError('Invalid independent-client AUC')
        groups[key(record)[:3]].append(value)
    return [dict(dataset=d, alpha=a, method=m, n=3,
                 mean_auc=statistics.mean(groups[d, a, m]),
                 sample_sd_auc=statistics.stdev(groups[d, a, m]),
                 endpoint='independent_client_mean_masked_task_macro_test_auc')
            for d, a, m in itertools.product(DATASETS, ALPHAS, METHODS)]


def load_records():
    records = [r for r in rows(SOURCE) if r['setting'] == 'client_local']
    coverage = {key(r): r for r in rows(COVERAGE)}
    sources = {r['source_csv']: r['source_sha256'] for r in records}
    for source, digest in sources.items():
        if sha(ROOT / source) != digest:
            raise ValueError('Audited source changed: ' + source)
    for r in records:
        c = coverage[key(r)]
        if (int(r['seed']) != int(r['split_seed']) or int(r['seed']) != int(r['partition_seed'])
                or c['derivation'] != 'analytical_constant_fallback_no_refit'
                or abs(float(c['mean_local_test_auc_all_tasks']) - float(r['primary_test_auc'])) > 1e-12):
            raise ValueError('Seed/coverage convention mismatch')
    return records


def latex(summary):
    lookup = {(r['dataset'], r['alpha'], r['method']): r for r in summary}
    lines = [r'% Generated by build_traditional_supplement_20260924.py.',
             r'\begin{table}[H]', r'\centering',
             r'\caption{Independent-client fingerprint baselines on molecular classification datasets.}',
             r'\label{tab:traditional_local}', r'\setlength{\tabcolsep}{10pt}',
             r'\renewcommand{\arraystretch}{1.15}', r'\begin{tabular}{lcccc}',
             r'\toprule', r'Dataset & $\alpha$ & LR & NB & RF \\', r'\midrule']
    for di, dataset in enumerate(DATASETS):
        for ai, alpha in enumerate(ALPHAS):
            cells = []
            for method in METHODS:
                r = lookup[dataset, alpha, method]
                cells.append('$%.2f \\pm %.2f$' % (100 * r['mean_auc'], 100 * r['sample_sd_auc']))
            lines.append(' & '.join([dataset if ai == 0 else '', str(alpha)] + cells) + r' \\')
        if di < len(DATASETS) - 1:
            lines.append(r'\midrule')
    lines += [r'\bottomrule', r'\end{tabular}', r'\vspace{0.5em}',
              r'\parbox{\linewidth}{\footnotesize\textit{Note:} Values are test ROC-AUC (\%) as mean $\pm$ sample SD over seeds 0, 1, and 2. Each seed-level score averages masked task-macro AUC across four independently trained client models on the common held-out test set. There is no parameter exchange or prediction ensemble. LR: logistic regression; NB: Bernoulli naive Bayes; RF: random forest. Only tasks with both observed test classes are scored. Unfittable client--task models receive the analytically evaluated constant-prediction fallback, AUC 0.5, rather than being omitted.}',
              r'\end{table}', '']
    return '\n'.join(lines)


def emit(path, text, check):
    if check:
        if not path.exists() or path.read_text() != text:
            raise ValueError('Stale generated output: ' + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def csv_text(records):
    stream = io.StringIO(newline='')
    writer = csv.DictWriter(stream, fieldnames=list(records[0]), lineterminator='\n')
    writer.writeheader()
    writer.writerows(records)
    return stream.getvalue()


def main(check=False):
    records = load_records()
    summary = summarize(records)
    comparisons = []
    for dataset, alpha in itertools.product(DATASETS, ALPHAS):
        local = max((r for r in summary if r['dataset'] == dataset and r['alpha'] == alpha),
                    key=lambda r: r['mean_auc'])
        federated = [r for r in rows(MAIN) if r['dataset'] == dataset and float(r['alpha']) == alpha]
        top = max(federated, key=lambda r: float(r['mean_auc']))
        spl = next(r for r in federated if r['method'] == 'fedavg_proto')
        comparisons.append(dict(dataset=dataset, alpha=alpha, local_best_method=local['method'],
            local_best_mean_auc=local['mean_auc'], highest_federated_method=top['method'],
            highest_federated_mean_auc=float(top['mean_auc']), fedspl_mean_auc=float(spl['mean_auc']),
            best_federated_minus_best_local_pp=100*(float(top['mean_auc'])-local['mean_auc']),
            fedspl_minus_best_local_pp=100*(float(spl['mean_auc'])-local['mean_auc']),
            interpretation='descriptive_server_vs_client_mean; not matched-model causal effect'))
    emit(TEX, latex(summary), check)
    emit(OUT / 'local_source_runs.csv', csv_text(records), check)
    emit(OUT / 'local_mean_sd.csv', csv_text(summary), check)
    emit(OUT / 'descriptive_endpoint_comparison.csv', csv_text(comparisons), check)
    audit = dict(source_runs=135, table_cells=45, new_training=0, main_table_changed=False,
                 selected_endpoint='independent client mean; no pooled or ensemble table',
                 source_sha256={str(p.relative_to(ROOT)): sha(p) for p in (SOURCE, COVERAGE, MAIN)},
                 evidence_limit='Source protocol, seed metadata and task records; no immutable per-run molecular ID certificate',
                 fallback='Analytical constant-prediction AUC for unfittable client-task pairs; no refitting')
    emit(OUT / 'table_audit.json', json.dumps(audit, indent=2, sort_keys=True) + '\n', check)
    print(json.dumps(dict(verified_runs=135, complete_cells=45,
        highest_federated_mean_above_local_best=sum(r['best_federated_minus_best_local_pp'] > 0 for r in comparisons),
        fedspl_mean_above_local_best=sum(r['fedspl_minus_best_local_pp'] > 0 for r in comparisons), check=check)))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    main(parser.parse_args().check)
